version: "3.8"

services:
  mouse:
    build: ./home
    hostname: home
    # volumes:
    #   - /etc/letsencrypt/live/kelseywilliams.co/privkey.pem:/etc/letsencrypt/live/kelseywilliams.co/privkey.pem:ro
    #   - /etc/letsencrypt/live/kelseywilliams.co/fullchain.pem:/etc/letsencrypt/live/kelseywilliams.co/fullchain.pem:ro
    networks:
      - site
    ports:
       - "3001:3001"
    healthcheck:
      test:  ["CMD", "curl", "-f", "http://home:3001"]
      interval: 10s
      timeout: 1s
networks:
  site:
    external: true

