version: "3.8"

services:
  mouse:
    build: ./home
    volumes:
        - ./home/backend/logs:/logs
    networks:
      - site
    ports:
       - "3001:3001"
    healthcheck:
      test:  ["CMD", "curl", "-f", "http://mouse:3001"]
      interval: 10s
      timeout: 1s
networks:
  site:
    external: true

